openapi: 3.0.3
info:
  title: CasaOS Local Storage API
  version: 0.3.0
servers:
  - url: http://localhost/v2
paths:
  /mount:
    get:
      summary: Get all mounted volumes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mount'
components:
  schemas:
    Mount:
      type: object
      properties:
        Id:
          type: integer
        Mountpoint:
          type: string
        Type:
          type: string
        Source:
          type: string
        Options:
          type: string