openapi: 3.0.3
info:
  title: CasaOS Local Storage API
  version: 0.3.0
servers:
  - url: http://localhost/v2
paths:
  /storage:
    get:
      summary: Get all storage devices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageDevice'
    post:
      summary: Create a new storage device
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageDevice'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageDevice'
components:
  schemas:
    StorageDevice:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - disk
            - partition
            - filesystem
        size:
          type: integer
          format: int64
        mountpoint:
          type: string
        uuid:
          type: string
        label:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/StorageDevice'